[package]
name = "simple-cast-gen"
version = "0.1.0"
authors = ["Christopher Field <cfield2@gmail.com>"]
description = "Generate asciinema cast files without recording"
license = "GPL-3.0"
edition = "2018"
readme = "README.md"
repository = "https://github.com/volks73/simple-cast-gen"
documentation = "https://volks73.github.io/simple-cast-gen"
categories = ["development-tools"]
keywords = ["asciinema"]
homepage = "https://github.com/volks73/simple-cast-gen"
exclude = ["/.github"]

[[bin]]
name = "simple-cast-gen"

[dependencies]
anyhow = "1.0"
clap-verbosity-flag = "0.3"
env_logger = "0.8"
log = "0.4"
structopt = "0.3"

[badges]
is-it-maintained-issue-resolution = { repository = "volks73/simple-cast-gen" }
is-it-maintained-open-issues = { repository = "volks73/simgple-cast-gen" }
